name: trwiki
label: Turkish Wikipedia
host: tr.wikipedia.org

samples:
    20k_2015:
        labeling_campaign: "https://labels.wmflabs.org/campaigns/trwiki/5/"

wikilabels_sample: 20k_2015
default_sample: 20k_2015

merged_samples:
    20k_2015:
        human_labeled_revisions: "20k_2015"

models:
    damaging:
        pop_rate_true: 0.0495014425266994
    goodfaith:
        pop_rate_true: 0.9538897605911829

trusted_groups:
    - sysop
    - oversight
    - trusted
    - bot
    - rollbacker
    - checkuser
    - abusefilter
    - bureaucrat
